/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as ItinerairesRouteImport } from './routes/itineraires'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RapportRouteImport } from './routes/rapport'
import { Route as RoleRouteImport } from './routes/role'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as AireZoneIdAreaRouteImport } from './routes/aire.$zoneId.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerairesRoute = ItinerairesRouteImport.update({
  id: '/itineraires',
  path: '/itineraires',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportRoute = RapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const AireZoneIdAreaRoute = AireZoneIdAreaRouteImport.update({
  id: '/aire/$zoneId/$area',
  path: '/aire/$zoneId/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRoute
  '/itineraires': typeof ItinerairesRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/rapport': typeof RapportRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/zones': typeof ZonesRoute
  '/aire/$zoneId/$area': typeof AireZoneIdAreaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRoute
  '/itineraires': typeof ItinerairesRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/rapport': typeof RapportRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/zones': typeof ZonesRoute
  '/aire/$zoneId/$area': typeof AireZoneIdAreaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRoute
  '/itineraires': typeof ItinerairesRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/rapport': typeof RapportRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/zones': typeof ZonesRoute
  '/aire/$zoneId/$area': typeof AireZoneIdAreaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/incidents'
    | '/itineraires'
    | '/login'
    | '/profil'
    | '/rapport'
    | '/role'
    | '/signup'
    | '/zones'
    | '/aire/$zoneId/$area'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/incidents'
    | '/itineraires'
    | '/login'
    | '/profil'
    | '/rapport'
    | '/role'
    | '/signup'
    | '/zones'
    | '/aire/$zoneId/$area'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/incidents'
    | '/itineraires'
    | '/login'
    | '/profil'
    | '/rapport'
    | '/role'
    | '/signup'
    | '/zones'
    | '/aire/$zoneId/$area'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  IncidentsRoute: typeof IncidentsRoute
  ItinerairesRoute: typeof ItinerairesRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  RapportRoute: typeof RapportRoute
  RoleRoute: typeof RoleRoute
  SignupRoute: typeof SignupRoute
  ZonesRoute: typeof ZonesRoute
  AireZoneIdAreaRoute: typeof AireZoneIdAreaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraires': {
      id: '/itineraires'
      path: '/itineraires'
      fullPath: '/itineraires'
      preLoaderRoute: typeof ItinerairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport': {
      id: '/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof RapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aire/$zoneId/$area': {
      id: '/aire/$zoneId/$area'
      path: '/aire/$zoneId/$area'
      fullPath: '/aire/$zoneId/$area'
      preLoaderRoute: typeof AireZoneIdAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  IncidentsRoute: IncidentsRoute,
  ItinerairesRoute: ItinerairesRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  RapportRoute: RapportRoute,
  RoleRoute: RoleRoute,
  SignupRoute: SignupRoute,
  ZonesRoute: ZonesRoute,
  AireZoneIdAreaRoute: AireZoneIdAreaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
